<?php
/**
 * This class is autogenerated by the Spapi class generator
 * Specification: https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-model
 *
 *
 * Selling Partner API for Catalog Items
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 */
namespace SellingPartner\Api;

use SellingPartner\Core\Client;

class CatalogItems extends Client {
	
	/**
	 * Operation searchCatalogItems
	 *
	 * @param array $queryParams
	 *
	 */
	public function searchCatalogItems($queryParams = [])
	{
		return $this->send("/catalog/2022-04-01/items", [
			'method' => 'GET',
			'query' => $queryParams,
		]);
	}
	
	/**
	 * Operation getCatalogItem
	 *
	 * @param string $asin The Amazon Standard Identification Number (ASIN) of the item.
	 *
	 * @param array $queryParams
	 *    - *marketplaceId* string - A marketplace identifier. Specifies the marketplace for the item.
	 *
	 */
	public function getCatalogItem($asin, $queryParams = [])
	{
		return $this->send("/catalog/2022-04-01/items/{$asin}", [
			'method' => 'GET',
			'query' => $queryParams,
		]);
	}
}
