<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2020-12-22
* Specification: https://github.com/amzn/selling-partner-api-models/blob/main/models/uploads-api-model/uploads_2020-11-01.json
* Source MD5 signature: 20f4a707fa1bd67af44c4a2c4c6fdf51
*
*
* Selling Partner API for Uploads
* The Selling Partner API for Uploads provides operations that support uploading files.
*/
namespace SellingPartner\Api;

use SellingPartner\Core\Client;

class Tokens extends Client {

  /**
  * Operation createRestrictedDataToken
  *
  * @param array $queryParams
  *    Returns a Restricted Data Token (RDT) for one or more restricted resources that you specify. A restricted resource is the HTTP method and path from a restricted operation that returns Personally Identifiable Information (PII), plus a dataElements value that indicates the type of PII requested. See the Tokens API Use Case Guide for a list of restricted operations. Use the RDT returned here as the access token in subsequent calls to the corresponding restricted operations.
  *
  */
  public function createRestrictedDataToken($queryParams = [])
  {
    return $this->send("/tokens/2021-03-01/restrictedDataToken", [
      'method' => 'POST',
      'json' => $queryParams,
    ]);
  }
}
